import { IColumn } from "@fluentui/react";

export const column: IColumn[] = [
  {
    key: "column1",
    name: "Cliente",
    fieldName: "nCliente",
    minWidth: 30,
    maxWidth: 30,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
  {
    key: "column2",
    name: "N°",
    fieldName: "nActivity",
    minWidth: 30,
    maxWidth: 30,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
  {
    key: "column6",
    name: "Inicio",
    fieldName: "dateStart",
    minWidth: 70,
    maxWidth: 70,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
  {
    key: "column3",
    name: "Producto",
    fieldName: "product",
    minWidth: 90,
    maxWidth: 90,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
  {
    key: "column4",
    name: "Codigo",
    fieldName: "codeActivity",
    minWidth: 70,
    maxWidth: 70,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
  {
    key: "column7",
    name: "Final",
    fieldName: "dateEnd",
    minWidth: 70,
    maxWidth: 70,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
  {
    key: "column8",
    name: "Duracion",
    fieldName: "duration",
    minWidth: 70,
    maxWidth: 70,
    isRowHeader: true,
    isResizable: true,
    isSorted: true,
    isSortedDescending: false,
    sortAscendingAriaLabel: "Sorted A to Z",
    sortDescendingAriaLabel: "Sorted Z to A",
    data: "string",
    isPadded: true,
  },
];